#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config top_padding          27
bspc config border_width         0
bspc config window_gap           `expr 12 * $GDK_SCALE`

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Org.gnome.Nautilus   desktop='^1' state=pseudo_tiled follow=on
bspc rule -a TelegramDesktop      desktop='^1' state=floating     follow=on
bspc rule -a Nextcloud            desktop='^1' state=pseudo_tiled follow=on
bspc rule -a "*:transgui"         desktop='^1' state=floating     follow=on
bspc rule -a Google-chrome        desktop='^2'                    follow=on
bspc rule -a baka-mplayer                      state=floating     sticky=on

function kill_program {
  if ps -A | grep $1; then
    killall -q $1
  fi
}

kill_program gnome-keyring-daemon
kill_program picom
kill_program pasystray
kill_program polybar
kill_program dunst
kill_program polkit-gnome-authentication-agent-1
kill_program gsd-xsettings

gnome-keyring-daemon --start --components=pkcs11 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/gsd-xsettings &
feh --bg-scale ${HOME}/.config/wallpaper.png
xsetroot -cursor_name left_ptr
picom --experimental-backends &
polybar mybar &
fcitx5 &
dunst &
sxhkd &
dex -a
libinput-gestures-setup restart

xinput set-prop "bcm5974" "libinput Natural Scrolling Enabled" 1
xinput set-prop 'Logitech G102 LIGHTSYNC Gaming Mouse' 'libinput Natural Scrolling Enabled' 1
xinput set-prop 'Logitech G102 LIGHTSYNC Gaming Mouse' 'libinput Accel Speed' -0.5
