#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             30
spacebar -m config spacing_left       25
spacebar -m config spacing_right      15
spacebar -m config text_font          "TerminessTTF Nerd Font:Normal:17.0"
spacebar -m config icon_font          "TerminessTTF Nerd Font:Bold:17.0"
spacebar -m config background_color   0xff282a36
spacebar -m config foreground_color   0xffa8a8a8
spacebar -m config space_icon_color   0xffbd93f9
spacebar -m config power_icon_color   0xffcd950c
spacebar -m config battery_icon_color 0xffd75f5f
spacebar -m config dnd_icon_color     0xffa8a8a8
spacebar -m config clock_icon_color   0xffa8a8a8
spacebar -m config space_icon_strip   1: 2: 3: 4: 5:
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%y/%m/%d %R"

